#Shutter main window
panelShutter=Shutter Encoder

#grpChooseFiles
grpChooseFiles=Pilih file
btnBrowse=Telusuri...
btnEmptyList=Hapus
btnReset=Atur Ulang
lblTermine=0 Selesai
fileEnded=Selesai
filesEnded=Selesai
import=Impor item
file=File
files=File
dropFilesHere=Seret file ke sini
filesVideoOrAudio=File video atau audio
fileVideoAndAudio=File video atau audio
filesVideoOrAudioOrPicture=File video, audio, atau gambar
filesVideoOrPicture=File video atau gambar
filesVideo=File video
fileVideo=File video
fileMaster=File master dan file video sisipan

#grpChooseFunction
grpChooseFunction=Pilih fungsi
btnStartFunction=Mulai fungsi
btnPauseFunction=Jeda
btnResumeFunction=Lanjutkan
btnStopRecording=Hentikan perekaman
btnAddToRender=Tambahkan ke antrian
btnDownload=Unduh video
btnCancel=Batal
lblFilter=Filter:
levels=Level:
shortest=terpendek
longest=terpanjang
aucun=tidak ada
mode=Mode:
audio=Audio
video=Video

#grpDestination
output=Output 
sameAsSource=Sama dengan sumber
caseSendMail=Kirim email ringkasan
textMail=Alamat email anda
caseStream=Aktifkan streaming
caseLoop=Memutar
caseOpenFolderAtEnd=Buka folder tujuan setelah selesai
caseChangeFolder=Ubah
caseDeleteSourceFile=Hapus file sumber
aucune=Tidak ada
shutterEncodingCompleted=Pengkodean Shutter Encoder selesai
shutterEncodingError=Masalah pengkodean Shutter Encoder
notEncoded=Tidak dapat dikodekan.
isEncoded=Telah dienkode di:

#grpProgression
lblEncodageEnCours=Tanpa pengkodean
waitingFiles=Menunggu file...
processCancelled=Proses dibatalkan
processEnded=Proses selesai
grpProgression=Status pemajuan  
saveZip=Menyimpan file ZIP
compression=Proses kompresi sedang berlangsung...
decompression=Proses dekompresi sedang berlangsung...
createBurnFiles=Membuat file untuk dibakar...
babEncoding=Penggabungan sedang berlangsung...
createOpatomFiles=Membuat file OP-Atom
createAS10Format=Membuat format AS-10
caseRunInBackground=Pekerjaan saat tidak aktif
btnDisableAnimations=Nonaktifkan animasi
btnDisableSound=Nonaktifkan suara akhir
btnDisableUpdate=Nonaktifkan pembaruan
btnDisableVideoPlayer=Nonaktifkan pemutar video
btnDisableMinimizedWindow=Nonaktifkan jendela yang diperkecil
btnPreventSleepMode=Cegah mode tidur
btnEmptyListAtEnd=Kosongkan daftar saat proses selesai
btnEndingAction=Akhiri tindakan:
btnCustomFFmpegPath=Gunakan ffmpeg lokal:
lblActionClose=tutup Shutter Encoder
lblActionShutdown=matikan komputer
analyzing=Analisis sedang berlangsung:
getVideoName=Mengambil judul video
getAvailableFormats=Mengambil format yang tersedia

#StatusBar
lblCrParPaul=oleh Paul Pacifico
tempsRestant=Waktu tersisa:
tempsEcoule=Waktu berlalu:
timePause=Waktu tersisa: Ditunda
firstPass=Lintasan pertama
secondPass=Lintasan kedua

#grpImageSequence
grpSequenceImage=Urutan gambar
caseActiverSequence=Aktifkan urutan gambar ke:
caseBlend=Pencampuran bingkai: x0
blend=Pencampuran bingkai:
caseMotionBlur=Tambahkan buram gerak

#grpImage
grpResolution=Gambar
caseCreateSequence=Buat urutan gambar dari video
lblInterpretation=Interpretasikan rekaman video ke:
caseRotate=Rotasi:
caseAngle=Sudut:
caseMiror=Cermin
posX=Posisi X:
posY=Posisi Y:

#grpImageFilter
grpFiltreImage=Filter
caseYear=Tahun:
caseMonth=Bulan:
caseDay=Hari:
caseFrom=Slot waktu:

#grpColorimetry
grpColorimetry=Kolorimetri
btnManage=Kelola
caseLUTs=Terapkan LUT:
caseGamma=Tingkat gamma:
caseLevels=Konversi tingkat:
caseColormatrix=Konversi ruang warna:
caseColorspace=Ruang warna:

#grpInAndOut
cutUpper=Potong
removeMode=Hapus
splitMode=Pisahkan
enable=Aktifkan

#grpAudio
grpAudio=Pengaturan audio
mono=Mono
stereo=Stereo
codecCopy=Salin
noVideo=Tanpa video
noAudio=Tanpa audio
custom=Kustom
caseAudioCodec=Konversi:
caseAudioOffset=Offset:
caseKeepSourceTracks=Pertahankan trek audio sumber
caseSampleRate=Ubah laju sampel menjadi:
caseMixAudio=Campur file audio ke:
caseSplitAudio=Pisahkan trek audio ke:
caseConvertAudioFramerate=Konversi dari:

#grpOverlay
caseAddTimecode=Tampilkan
caseAddOverlay=Hamparkan
caseShowTimecode=Tampilkan kode waktu internal video
caseShowFileName=Tampilkan nama file
caseShowText=Tampilkan teks:
lblTimecode=kode waktu
lblFrameNumber=frame N 

#grpTimecode
grpTimecode=Kode waktu
caseSetTimecode=Atur kode waktu:
caseIncrementTimecode=Penambahan otomatis
caseGenerateFromDate=Buat kode waktu dari tanggal
caseReadAudioTimecode=Baca kode waktu audio

#grpCorrections
grpCorrections=Koreksi
caseAddGrain=Butir film:

#grpTransitions
grpTransitions=Transisi
lblVideoFadeIn=Fade-in video:
lblVideoFadeOut=Fade-out video:
lblAudioFadeIn=Fade-in audio:
lblAudioFadeOut=Fade-out audio:
white=putih
black=hitam

#grpAdvanced
grpAdvanced=Fitur lanjutan
smoothExposure=Pemulusan eksposur:
noiseSuppression=Peredaman noise:
details=Detail:
accel=Akselerasi perangkat keras
chooseLogo=Pilih tanda air
chooseSubtitles=Pilih file subtitle
preview=Pratinjau
caseForcerProgressif=Paksa ke progresif
caseForcerEntrelacement=Paksa interlacing
caseForcerInversion=Paksa inversi medan
caseForcerDesentrelacement=Paksa deinterlacing:
caseForcerDAR=Paksa tampilkan:
caseLimiter=Batasi output ke 16-235
caseCreateTree=Pertahankan hierarki folder
casePreserveMetadata=Pertahankan metadata
caseCookies=Gunakan cookie dari browser:
casePreserveSubs=Pertahankan subtitle
caseCreateOPATOM=Buat dalam
lblCreateOPATOM=format
caseOPATOM=Sumber dalam format OP-Atom (P2, Canon XF, Sony...)
caseSubtitles=Tambahkan subtitle
caseStabilisation=Stabilkan gambar
caseDeflicker=Deflicker
caseExposure=Penghalusan eksposur: 0
caseBruit=Peredaman noise: 0
caseBanding=Kurangi banding
caseDetails=Detail: 0.0
caseDecimate=Hapus bingkai duplikat
caseConform=Sesuaikan dengan:
conformByReverse=Balik
conformBySpeed=Kecepatan
conformByDrop=Turunkan
conformByBlending=Pencampuran
conformByInterpolation=Interpolasi
conformBySlowMotion=Gerakan sangat lambat
caseAccel=Akselerasi perangkat keras:
caseForceOutput=Paksakan output:
caseFastStart=Aktifkan mulai cepat
caseFastDecode=Aktifkan dekode cepat
caseVarianceBoost=Aktifkan peningkatan varians
caseAlpha=Aktifkan kanal alfa
alphaStraight=lurus
alphaPremultiply=premultiplied
caseGOP=Atur GOP ke:
caseFilmGrain=Atur butiran film ke:
caseFilmGrainDenoise=Atur penghilang noise butiran film ke:
caseCABAC=Atur pengkodean entropi ke CAVLC
caseChunks=Atur potongan ke:
caseDRC=Aktifkan DRC
caseForceLevel=Paksa profil:
caseForcePreset=Paksa preset:
caseForceTune=Paksa penyetelan:
caseForceSpeed=Paksa kecepatan:
caseForceQuality=Paksa kualitas:
caseLogo=Tanda air
caseAS10=Buat format AS-10:

#grpBitrate
grpBitrate=Penyesuaian bitrate
lblBitrateTimecode=Durasi:
lblBitrateSize=Skala:
lblH=h
lblSec=s
lblPad=Sesuaikan
lblCrop=Pangkas
lblStretch=Regangkan
lblVideoBitrate=Bitrate video:
lblValue=Nilai:
lblMaximumBitrate=Maksimum:
lblAudioBitrate=Bitrate audio:
lblFromTo=hingga:
lblBest=Terbaik
lblGood=Baik
lblWorst=Terburuk
source=Sumber
size=Ukuran:
mo=MB
case2pass=2-pass
caseQMax=Kualitas Maks.

#MenuItems
menuItemVisualiser=Tampilkan
menuItemSilentTrack=Tambahkan trek audio bisu
menuItemOuvrirDossier=Buka lokasi file
menuItemInfo=Informasi file...
menuItemRename=Ubah nama file
menuItemInputDevice=Rekam layar/perangkat
menuItemArborescence=Salin pohon
menuItemHash=Buat hash
menuItemTempsTotal=Durasi total file
menuItemPoids=Ukuran perkiraan file
menuItemGop=Struktur GOP
menuItemFtp=Kirim ke server FTP
menuItemZip=Buat arsip ZIP
menuItemUnzip=Ekstrak arsip
menuItemStartScan=Pantau folder
menuItemStopScan=Hentikan pemindaian
menuItemOpenFolder=Buka folder
menuItemConsole=Tampilkan konsol

#Functions
itemAITools=- Alat AI:
itemNoConversion=- Tanpa konversi:
itemAudioConversion=- Konversi audio:
itemEditingCodecs=- Codec pengeditan:
itemOuputCodecs=- Codec keluaran:
itemBroadcastCodecs=- Codec siaran:
itemOldCodecs=- Codec lama:
itemArchiveCodecs=- Codec arsip:
itemBurnRip=- Bakar & Rip:
itemImage=- Pembuatan gambar:
itemAnalyze=- Analisis:
itemDownload=- Unduh:
itemMyFunctions=Fungsi saya...	
functionCut=Potong tanpa pengkodean ulang
functionRewrap=Rewrap
functionConform=Sesuaikan
functionExtract=Ekstrak
functionInsert=Sisipan video
functionSeparation=Pemisahan audio
functionTranscribe=Transkripsi audio
functionTranslate=Terjemahkan teks
functionColorize=Warnai
functionBlurFaces=Mengaburkan wajah
functionBackgroundRemover=Penghapus latar belakang
functionMerge=Gabungkan
functionReplaceAudio=Ganti audio
functionSubtitles=Teks terjemahan
functionPicture=Gambar
functionNormalization=Normalisasi audio
functionSceneDetection=Deteksi pemotongan
functionBlackDetection=Deteksi hitam
functionOfflineDetection=Deteksi media offline
functionWeb=Video web

#Console
btnSave=Simpan
saveConsole=Simpan Konsol
followLine=Gulir mengikuti teks

#ColorImage
frameColorImage=Penyesuaian warna
lblExposure=Paparan:
lblGamma=Gamma:
lblHighlights=Sorotan:
lblMediums=Nada tengah:
lblShadows=Bayangan:
lblWhite=Warna putih:
lblBlack=Warna hitam:
lblBalance=Keseimbangan putih:
lblHUE=Semburat:
lblContrast=Kontras:
lblGrain=Penghalusan/Penajaman:
lblVignette=Pemvinyetan:
lblSaturation=Saturasi:
lblVibrance=Daya hidup warna:
lblRGB=RGB:
lblRED=Merah:
lblGREEN=Hijau:
lblBLUE=Biru:
lblZoom=Zoom:
intensity=Intensitas
red=Merah
green=Hijau
blue=Biru
setAll=Semua
setHigh=Tinggi
setMedium=Sedang
setLow=Rendah

#CropImage
frameCropImage=Memotong
btnApply=Terapkan
lblWidth=Lebar:
lblHeight=Tinggi:
cantLoadFile=Tidak dapat memuat file
error=Kesalahan

#CropVideo
wrongValue=Nilai anda salah
wrongFormat=Kesalahan format
lblPresets=Pengaturan awal:

#CutDetection
frameDetectionCoupe=Deteksi potongan
btnAnalyse=Analisis baru
lblSensibility=Sensitivitas:
btnEDL=Ekspor ke EDL
saveEDL=Simpan EDL
cut=potong
fileCreated=Pembuatan file selesai
chooseFileName=Pemilihan nama file
lblEdit=Edit menggunakan tombol hapus.
menuItemCopyTimecode=Salin kode waktu
notProcessedFiles=File berikut tidak dapat diproses:
encodingError=Masalah pengkodean

#RenderQueue
frameFileDeRendus=Antrian Render
columnFile=File
columnCommand=Perintah
btnStartRender=Jalankan antrian render
caseRunParallel=Jalankan secara paralel
destination=Tujuan

#MyFunctions
frameFonctions=Fungsi saya
lblSaveMac=Tekan Command + S untuk menyimpan fungsi
lblSavePC=Tekan Ctrl + S untuk menyimpan fungsi
lblDrop=Atau seret fungsi Anda ke sini
menuItemDelete=Hapus fungsi
menuItemUpdate=Perbarui fungsi
menuItemLoad=Muat fungsi

#Ftp
frameFtp=Server FTP
lblFtp=Alamat FTP:
lblUser=Pengguna:
lblPassword=Kata sandi:
checkIdentity=Periksa kredensial Anda
wrongIdentity=Kredensial salah
connectionRefused=Koneksi tidak dapat dibuat
connectionError=Masalah dalam menghubungi server
sendingFile=Pengiriman sedang berlangsung:
sendingSuccessful=Pengiriman ke Server FTP berhasil
sendingFailed=Pengiriman ke server FTP gagal
sendingCancelled=Pengiriman ke server FTP dibatalkan
shutterMailFailed=Pengiriman Shutter Encoder ke FTP Gagal
shutterMailSuccessful=Pengiriman Shutter Encoder ke FTP Berhasil
theFile=File:
notSended=Tidak dapat dikirim ke:
isSended=Sudah dikirim ke:
mailSuccessful=Pengiriman email berhasil
mailFailed=Email gagal

#WeTransfer
lblMessage=Pesan:
lblYourMail=Email Anda:
lblRecipient=Penerima:
sentFrom=Dikirim dari www.shutterencoder.com
textTo=Alamat dipisahkan dengan spasi
casePlus=Akun WeTransfer Plus
sendingWTSuccessful=Pengiriman WeTransfer berhasil
sendingWTFailed=Pengiriman WeTransfer gagal
sendingWTCancelled=Pengiriman WeTransfer dibatalkan
link=Tautan WeTransfer:
linkError=Kesalahan unggah WeTransfer
linkCopied=Tautan WeTransfer disalin ke papan klip

#GOP
analyzeOf=Analisis file:
of=dari

#Informations
frameInformations=Informasi
lblWait=Analisis sedang berlangsung, mohon tunggu...

#VideoPlayer
btnCancel=Batalkan
casePlaySound=Audio per bingkai
caseVuMeter=Vu-meter
caseGPU=Gunakan GPU
caseTcInterne=Tampilkan kode waktu video
lblDuree=Durasi:
lblTotalFrames=bingkai

#Logo
frameLogo=Tambahkan tanda air
caseSafeArea=Area aman
lblSize=Ukuran:
lblOpacity=Opasitas

#MiniWindow
lblEnCours=Tidak ada file yang sedang diproses

#Settings
frameSettings=Pengaturan
lblThreads=Tentukan jumlah utas yang digunakan (0 = otomatis):
lblScreenRecord=Tentukan kecepatan bingkai perekaman layar:
lblInputDevice=Atur kecepatan bingkai perangkat input:
lblImageToVideo=Atur durasi gambar statis menjadi:
lblFrames=bingkai
btnSetBab=Proses daftar file sebagai Gabung
btnOpenGOP=Atur fungsi menjadi Open-GOP
casePrefix=Tambahkan awalan:
btnExtension=Tambahkan akhiran:
caseSubFolder=Buat subfolder:
btnExclude=Kecualikan ekstensi:
btnHidePath=Sembunyikan jalur daftar file
btnLoadPreset=Muat saat startup:
btnWaitFileComplete=Tunggu secara otomatis hingga file siap
toDefault=standar:
lastUsed=Terakhir digunakan
lblGpuDecoding=Dekoding GPU:
lblGpuFiltering=Penyaringan GPU:
lblStrictMode=Atur mode ketat ke:
lblScaleMode=Atur mode skala ke:
btnNoUpscale=Jangan tingkatkan resolusi yang lebih rendah
btnPreviewOutput=Pratinjau kualitas output akhir (eksperimental)
lblSyncMode=Atur mode framerate:
lblLanguage=Atur bahasa ke:
lblTheme=Atur warna sorotan:

#RenameWindow
frameRenommage=Ubah nama file
btnLimit=Batasi jumlah karakter menjadi:
btnIncrementer=Tingkatkan dari:
lblRemplacer=Ganti:
lblPar=Dengan:
lblExemple=Contoh:
renommer=Ubah nama
btnAjouterAvant=Di depan:
btnAjouterApres=Di belakang:
convertToLower=Ubah menjadi huruf kecil
convertToUpper=Ubah menjadi huruf besar
removeSpecialCharacters=Hapus karakter khusus
filesAlreadyExists=File telah ada

#Subtitles
lblTimeline=Garis waktu
lblSubtitlesPosition=Y:
frameAddSubtitles=Tambahkan teks dialog
lblFont=Jenis huruf:
lblsubtitleNumber=N° teks dialog
lblColor=Warna:
lblBackgroundOff=Garis tepi
lblBackgroundOn=Latar belakang
btnG=B
frameSubtitles=Penambahan teks dialog
integrateSRT=Apakah Anda ingin menambahkan teks dialog ke video?
subtitles=Teks dialog
lblTexte=Teks:
lblHelp=Bantuan
subtitlesLower=teks dialog
btnAdd=Tambahkan
btnModify=Mengedit
btnDelete=Hapus
deleteConfirmation=Konfirmasi penghapusan?
subtitlesDelete=Menghapus teks dialog
btnDebut=Mulai
btnFin=Akhir
lblOffset=Pergeseran:
caseShowWaveform=Tampilkan bentuk gelombang
caseShowThumbnails=Tampilkan thumbnail
txtShortcuts=Gunakan tombol Tab untuk beralih antara garis waktu dan teks:\r\n\r\n- Mulai/Akhir: I dan O\r\n- Teks diallog Berikutnya/Sebelumnya: panah atas/bawah\r\n- Maju/Mundur satu gambar: panah kiri/kanan\n- Mundur/Maju 10 gambar: J dan L\r\n- Tampilkan/Sembunyikan bentuk gelombang: W\r\n- Putar/Jeda: spasi atau K\r\n- Potong: C\r\n- Hapus: backspace atau del.\r\n- Tambahkan: enter\r\n\r\nPintasan yang tersedia dengan menekan tombol CTRL:\r\n\r\n- Miring: I\r\n- Tebal: B\r\n
chooseColor=Pilih warna
subtitlesFileError=File teks dialog tidak valid
invalidSubtitles=File Anda harus berformat SRT/VTT/SSA/ASS/SCC

#SubtitlesEdit
frameSubtitlesEdit=Edit semua teks

#Equalizer
frameEqualizer=Ekualiser

#WebVideo
lblURL=URL:
panelWebVideo=Unduh
frameVideoWeb=URL video
videoUrl=URL video
textURL=http://www.yourvideo.com
caseUser=Pengguna:
casePass=Kata sandi:
caseVideoPass=Kata sandi video:
update=Sedang diperbarui
MenuItemPaste=Tempel
invalidUrl=Periksa URL dan/atau nama pengguna/kata sandi Anda
downloadError=Masalah unduhan
lblQualit=Kualitas:
caseMP3=Konversi ke MP3
caseWAV=Konversi ke WAV
convertToWAV=Konversi ke wav
convertToMP3=Konversi ke mp3

#Update
lblNewVersion=Mengunduh versi baru...
frameUpdate=Perbarui Shutter Encoder
wantToDownload=Apakah Anda ingin mengunduhnya?
updateAvailable=Pembaruan tersedia
installNewVersion=Apakah Anda ingin menginstal versi baru?
downloadEnded=Pengunduhan selesai
downloadCancelled=Pengunduhan dibatalkan
downloadStopped=Pengunduhan terputus
downloadFailed=Pengunduhan gagal!
downloadError=Masalah unduhan
downloadModel=Pilih model AI

#Tooltips
newInstance=Instans baru
rightClick=Klik kanan tersedia...
tooltipMixAudio=Jika sumbernya mono -> file genap di kiri, ganjil di kanan
tooltipProgressif=Untuk menghilangkan interlacing pada video, gunakan kotak terkait / Mencentang kotak ini saja memungkinkan peralihan dari PsF ke progresif
tooltipEntrelacement=Jika sumber 50p (59,94p,60p), selang-seling ke 50i (59,94i,60i)
tooltipCreateOpatom=Seret file .mdb ke dalam bin Anda setelah memindai file dengan Avid
tooltipDetails=Berguna untuk menghilangkan distorsi dari video


#Messages
colon=:
fps=fps
yes=Ya
no=Tidak
yesToAll=Ya untuk semua
noToAll=Tidak untuk semua
btnKeep=Simpan
btnSkip=Lewati
btnOverwrite=Timpakan
caseApplyToAll=Terapkan ke semua
cutOnKeyframesOnly=Fungsi ini hanya memotong pada keyframe
noAccel=Tidak ada akselerasi perangkat keras yang tersedia\r\nPastikan driver Anda sudah diperbarui!
replaceAudioMissing=Anda memerlukan minimal satu klip video dan satu klip audio dalam daftar
missingElement=Elemen hilang
selectedFiles=File terpilih
ChooseDifferentFolder=Pilih folder tujuan yang berbeda
sameFolder=Folder pemindaian dan tujuan identik!
scanIncompatible=Fungsi tidak kompatibel dengan folder pemantauan
scanActivated=Folder pemantauan diaktifkan
addInputDevice=Tambahkan perangkat masukan?
incompatibleInputDevice=Perangkat masukan tidak kompatibel
approximativeWeight=Perkiraan berat
chooseFolderToCopy=Pilih folder untuk disalin
chooseDestinationFolder=Pilih folder tujuan
sameFolders=Folder tidak boleh identik
copyError=Kesalahan penyalinan
copyFinished=Penyalinan selesai
treeCopy=Tree Copy
chooseScanFolder=Pilih folder untuk dipindai
dragFolderToList=Seret folder Anda ke daftar
dragFolderToDestination=Seret folder Anda ke bagian tujuan
previewNotAvailable=Pratinjau tidak tersedia
areYouSure=Apakah Anda yakin?
restart=Mulai ulang aplikasi?
shutdown=Akan dimatikan dalam 60 detik
chooseExtension=Anda harus memilih ekstensi
extensionError=Masalah ekstensi
resume=Lanjutkan
isAlreadyStereo=Sudah dalam mode stereo
cantSplitAudio=Tidak dapat memisahkan trek
saveResult=Apakah Anda ingin menyimpan hasilnya?
analyzeEnded=Analisis selesai
noErrorDetected=Tidak ada kesalahan terdeteksi
noDVD=Tidak ada DVD di dalam drive
DVDMissing=DVD tidak ada
totalTime=Durasi total:
totalTimeFiles=Durasi total file
chooseResolution=Pilih resolusi:
resolution=Resolusi
to=ke
addFileToList=Silakan tambahkan file ke daftar
noFileInList=Tidak ada file di daftar
noFile=Tidak ada file
eraseFile=Apakah Anda ingin menimpa file ini?
File=File
alreadyExist=Sudah ada
cantAnalyzeGop=Tidak dapat menganalisis struktur GOP
analyzeError=Masalah analisis
shortTerm=Tidak ada jangka pendek yang lebih tinggi dari -16 LUFS
multitrack=Trek ganda terdeteksi
ChooseMultitrack=Pilih trek yang akan dianalisis:
opatomNoSound=Audio tidak akan disimpan dalam OP-Atom!
chooseSoftware=Pilih perangkat lunak Anda
chooseSubsIntegration=Apa yang ingin Anda lakukan?
subtitlesBurn=Bakar
subtitlesEmbed=Sematkan
mayNotWorkWithGOP=Mungkin tidak berfungsi dengan baik pada codec berbasis GOP
invalidCharacter=mengandung karakter yang tidak valid, mungkin tidak akan berfungsi dengan baik
sourceFile=Silakan pilih file sumber
ffmpeg=FFmpeg:
shutterTranscriberRequired=Fitur ini memerlukan Shutter Transcriber.
shutterAnonymizerRequired=Fitur ini memerlukan Shutter Anonymizer.
additionalFiles=File tambahan diperlukan.
downloadingAIModel=Mengunduh model AI

#OTHER
command=Perintah:
saveSettings=Menyimpan pengaturan
